spring.application.name=visa

# PostgreSQL Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/locationdb
spring.datasource.username=postgres
spring.datasource.password=miaritsoa
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#Mode developpement
spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true


spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp